name: prep-tutorials
on: 
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  prep-tutorials:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get commit message
        run: |
          readonly local msg=$(git log -1 --pretty=format:"%s")
          echo "COMMIT_MESSAGE=$msg" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          pip install nbformat
          
      - name: Process notebooks
        id: process_notebooks
        run: |
          python ci/process_tutorials.py

      - name: Commit post-processed files
        if: ${{ success() }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '*.ipynb'
          git add 'solutions/*.py'
          git add 'hints/*.md'
          git diff-index --quiet HEAD || git commit -m "Process tutorial notebooks"

      - name: Push post-processed notebooks
        if: ${{ success() }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
